Adding nginx combined log format
caddyserver/transform-encoder pull request #14
Opened 2022-03-14 09:50 UTC by ebanDev

2022-03-14 09:50 UTC, ebanDev commented
See #13 ;)

2022-03-14 16:09 UTC, mholt commented on README.md
> +format formatted `{request>remote_addr} - {request>user_id} [{ts}] "{request>method} {request>uri} {request>proto}" {status} {size} "{request>headers>Referer>[0]}" "{request>headers>User-Agent>[0]}"`
```suggestion
format transform `{request>remote_addr} - {request>user_id} [{ts}] "{request>method} {request>uri} {request>proto}" {status} {size} "{request>headers>Referer>[0]}" "{request>headers>User-Agent>[0]}"` {
```

2022-03-14 16:46 UTC, mohammed90 requested changes

2022-03-14 16:46 UTC, mohammed90 commented on README.md
> +## Nginx Combined Log Format Example
```suggestion
## Apache Combined Log Format Example
```

2022-03-14 18:42 UTC, mohammed90 requested changes
Thank you for adding another example of a common pattern! Since we're expanding into 2 examples now, can you please change the header into "Examples" with 2 sections, one for each example?

2022-03-14 19:41 UTC, ebanDev commented
Should be good :) (sry for the terrible naming of my commits x) ig you should squash them)

2022-03-19 23:43 UTC, mohammed90 approved these changes
Thank you so much for the addition! It will help more folks looking for that particularly common format.

2022-03-19 23:44 UTC, merged

2022-03-21 17:48 UTC, ebanDev commented
Pleasure ! :D

2022-03-21 17:48 UTC, ebanDev commented
Pleasure ! :D